// GENERATED by ts-rs (see src-tauri/build.rs or cargo test export_bindings).
// Do not edit by hand. Regenerate when Rust command/types change.
// This file will be populated in P0-T4 / IPC pipeline step.

export type AppHealth = {
  version: string;
  db_ok: boolean;
};

// Placeholder for future generated types (Project, Chat, etc.)
